server:
  port: 9922
---
spring:
  datasource:
    username: pilot
    password: 1234
    url: jdbc:mariadb://localhost:3306/pilot
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    open-in-view: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.sseung.pilot.seungpilotproject